apiVersion: v1
kind: Pod
metadata:
  name: deepfashion1
  labels:
    app: deepfashion1
spec:
  containers:
  - name: deepfashion1
    image: renjie.azurecr.io/deepfashion-gpu-image:latest
    command: ["sleep"]
    args: ["infinity"]
    stdin: true
    tty: true
    env:
    - name: GPU_CORE_UTILIZATION_POLICY
      value: "force"
    resources:
      limits:
        nvidia.com/gpu: 1
        nvidia.com/gpumem-percentage: 6
        nvidia.com/gpucores: 6
    volumeMounts:
    - name: shm
      mountPath: /dev/shm
  volumes:
  - name: shm
    emptyDir:
      medium: Memory
      sizeLimit: 32Gi
  restartPolicy: OnFailure
---
apiVersion: v1
kind: Pod
metadata:
  name: deepfashion2
  labels:
    app: deepfashion2
spec:
  containers:
  - name: deepfashion2
    image: renjie.azurecr.io/deepfashion-gpu-image:latest
    command: ["sleep"]
    args: ["infinity"]
    stdin: true
    tty: true
    env:
    - name: GPU_CORE_UTILIZATION_POLICY
      value: "force"
    resources:
      limits:
        nvidia.com/gpu: 1
        nvidia.com/gpumem-percentage: 6
        nvidia.com/gpucores: 6
    volumeMounts:
    - name: shm
      mountPath: /dev/shm
  volumes:
  - name: shm
    emptyDir:
      medium: Memory
      sizeLimit: 32Gi
  restartPolicy: OnFailure
---
apiVersion: v1
kind: Pod
metadata:
  name: deepfashion3
  labels:
    app: deepfashion3
spec:
  containers:
  - name: deepfashion3
    image: renjie.azurecr.io/deepfashion-gpu-image:latest
    command: ["sleep"]
    args: ["infinity"]
    stdin: true
    tty: true
    env:
    - name: GPU_CORE_UTILIZATION_POLICY
      value: "force"
    resources:
      limits:
        nvidia.com/gpu: 1
        nvidia.com/gpumem-percentage: 6
        nvidia.com/gpucores: 6
    volumeMounts:
    - name: shm
      mountPath: /dev/shm
  volumes:
  - name: shm
    emptyDir:
      medium: Memory
      sizeLimit: 32Gi
  restartPolicy: OnFailure
---
apiVersion: v1
kind: Pod
metadata:
  name: deepfashion4
  labels:
    app: deepfashion4
spec:
  containers:
  - name: deepfashion4
    image: renjie.azurecr.io/deepfashion-gpu-image:latest
    command: ["sleep"]
    args: ["infinity"]
    stdin: true
    tty: true
    env:
    - name: GPU_CORE_UTILIZATION_POLICY
      value: "force"
    resources:
      limits:
        nvidia.com/gpu: 1
        nvidia.com/gpumem-percentage: 6
        nvidia.com/gpucores: 6
    volumeMounts:
    - name: shm
      mountPath: /dev/shm
  volumes:
  - name: shm
    emptyDir:
      medium: Memory
      sizeLimit: 32Gi
  restartPolicy: OnFailure
---
apiVersion: v1
kind: Pod
metadata:
  name: deepfashion5
  labels:
    app: deepfashion5
spec:
  containers:
  - name: deepfashion5
    image: renjie.azurecr.io/deepfashion-gpu-image:latest
    command: ["sleep"]
    args: ["infinity"]
    stdin: true
    tty: true
    env:
    - name: GPU_CORE_UTILIZATION_POLICY
      value: "force"
    resources:
      limits:
        nvidia.com/gpu: 1
        nvidia.com/gpumem-percentage: 6
        nvidia.com/gpucores: 6
    volumeMounts:
    - name: shm
      mountPath: /dev/shm
  volumes:
  - name: shm
    emptyDir:
      medium: Memory
      sizeLimit: 32Gi
  restartPolicy: OnFailure
---
apiVersion: v1
kind: Pod
metadata:
  name: deepfashion6
  labels:
    app: deepfashion6
spec:
  containers:
  - name: deepfashion6
    image: renjie.azurecr.io/deepfashion-gpu-image:latest
    command: ["sleep"]
    args: ["infinity"]
    stdin: true
    tty: true
    env:
    - name: GPU_CORE_UTILIZATION_POLICY
      value: "force"
    resources:
      limits:
        nvidia.com/gpu: 1
        nvidia.com/gpumem-percentage: 6
        nvidia.com/gpucores: 6
    volumeMounts:
    - name: shm
      mountPath: /dev/shm
  volumes:
  - name: shm
    emptyDir:
      medium: Memory
      sizeLimit: 32Gi
  restartPolicy: OnFailure
---
apiVersion: v1
kind: Pod
metadata:
  name: deepfashion7
  labels:
    app: deepfashion7
spec:
  containers:
  - name: deepfashion7
    image: renjie.azurecr.io/deepfashion-gpu-image:latest
    command: ["sleep"]
    args: ["infinity"]
    stdin: true
    tty: true
    env:
    - name: GPU_CORE_UTILIZATION_POLICY
      value: "force"
    resources:
      limits:
        nvidia.com/gpu: 1
        nvidia.com/gpumem-percentage: 6
        nvidia.com/gpucores: 6
    volumeMounts:
    - name: shm
      mountPath: /dev/shm
  volumes:
  - name: shm
    emptyDir:
      medium: Memory
      sizeLimit: 32Gi
  restartPolicy: OnFailure
---
apiVersion: v1
kind: Pod
metadata:
  name: deepfashion8
  labels:
    app: deepfashion8
spec:
  containers:
  - name: deepfashion8
    image: renjie.azurecr.io/deepfashion-gpu-image:latest
    command: ["sleep"]
    args: ["infinity"]
    stdin: true
    tty: true
    env:
    - name: GPU_CORE_UTILIZATION_POLICY
      value: "force"
    resources:
      limits:
        nvidia.com/gpu: 1
        nvidia.com/gpumem-percentage: 6
        nvidia.com/gpucores: 6
    volumeMounts:
    - name: shm
      mountPath: /dev/shm
  volumes:
  - name: shm
    emptyDir:
      medium: Memory
      sizeLimit: 32Gi
  restartPolicy: OnFailure
---
apiVersion: v1
kind: Pod
metadata:
  name: deepfashion9
  labels:
    app: deepfashion9
spec:
  containers:
  - name: deepfashion9
    image: renjie.azurecr.io/deepfashion-gpu-image:latest
    command: ["sleep"]
    args: ["infinity"]
    stdin: true
    tty: true
    env:
    - name: GPU_CORE_UTILIZATION_POLICY
      value: "force"
    resources:
      limits:
        nvidia.com/gpu: 1
        nvidia.com/gpumem-percentage: 6
        nvidia.com/gpucores: 6
    volumeMounts:
    - name: shm
      mountPath: /dev/shm
  volumes:
  - name: shm
    emptyDir:
      medium: Memory
      sizeLimit: 32Gi
  restartPolicy: OnFailure
---
apiVersion: v1
kind: Pod
metadata:
  name: deepfashion10
  labels:
    app: deepfashion10
spec:
  containers:
  - name: deepfashion10
    image: renjie.azurecr.io/deepfashion-gpu-image:latest
    command: ["sleep"]
    args: ["infinity"]
    stdin: true
    tty: true
    env:
    - name: GPU_CORE_UTILIZATION_POLICY
      value: "force"
    resources:
      limits:
        nvidia.com/gpu: 1
        nvidia.com/gpumem-percentage: 6
        nvidia.com/gpucores: 6
    volumeMounts:
    - name: shm
      mountPath: /dev/shm
  volumes:
  - name: shm
    emptyDir:
      medium: Memory
      sizeLimit: 32Gi
  restartPolicy: OnFailure
---
apiVersion: v1
kind: Pod
metadata:
  name: deepfashion11
  labels:
    app: deepfashion11
spec:
  containers:
  - name: deepfashion11
    image: renjie.azurecr.io/deepfashion-gpu-image:latest
    command: ["sleep"]
    args: ["infinity"]
    stdin: true
    tty: true
    env:
    - name: GPU_CORE_UTILIZATION_POLICY
      value: "force"
    resources:
      limits:
        nvidia.com/gpu: 1
        nvidia.com/gpumem-percentage: 6
        nvidia.com/gpucores: 6
    volumeMounts:
    - name: shm
      mountPath: /dev/shm
  volumes:
  - name: shm
    emptyDir:
      medium: Memory
      sizeLimit: 32Gi
  restartPolicy: OnFailure
---
apiVersion: v1
kind: Pod
metadata:
  name: deepfashion12
  labels:
    app: deepfashion12
spec:
  containers:
  - name: deepfashion12
    image: renjie.azurecr.io/deepfashion-gpu-image:latest
    command: ["sleep"]
    args: ["infinity"]
    stdin: true
    tty: true
    env:
    - name: GPU_CORE_UTILIZATION_POLICY
      value: "force"
    resources:
      limits:
        nvidia.com/gpu: 1
        nvidia.com/gpumem-percentage: 6
        nvidia.com/gpucores: 6
    volumeMounts:
    - name: shm
      mountPath: /dev/shm
  volumes:
  - name: shm
    emptyDir:
      medium: Memory
      sizeLimit: 32Gi
  restartPolicy: OnFailure
---
apiVersion: v1
kind: Pod
metadata:
  name: deepfashion13
  labels:
    app: deepfashion13
spec:
  containers:
  - name: deepfashion13
    image: renjie.azurecr.io/deepfashion-gpu-image:latest
    command: ["sleep"]
    args: ["infinity"]
    stdin: true
    tty: true
    env:
    - name: GPU_CORE_UTILIZATION_POLICY
      value: "force"
    resources:
      limits:
        nvidia.com/gpu: 1
        nvidia.com/gpumem-percentage: 6
        nvidia.com/gpucores: 6
    volumeMounts:
    - name: shm
      mountPath: /dev/shm
  volumes:
  - name: shm
    emptyDir:
      medium: Memory
      sizeLimit: 32Gi
  restartPolicy: OnFailure
---
apiVersion: v1
kind: Pod
metadata:
  name: deepfashion14
  labels:
    app: deepfashion14
spec:
  containers:
  - name: deepfashion14
    image: renjie.azurecr.io/deepfashion-gpu-image:latest
    command: ["sleep"]
    args: ["infinity"]
    stdin: true
    tty: true
    env:
    - name: GPU_CORE_UTILIZATION_POLICY
      value: "force"
    resources:
      limits:
        nvidia.com/gpu: 1
        nvidia.com/gpumem-percentage: 6
        nvidia.com/gpucores: 6
    volumeMounts:
    - name: shm
      mountPath: /dev/shm
  volumes:
  - name: shm
    emptyDir:
      medium: Memory
      sizeLimit: 32Gi
  restartPolicy: OnFailure
---
apiVersion: v1
kind: Pod
metadata:
  name: deepfashion15
  labels:
    app: deepfashion15
spec:
  containers:
  - name: deepfashion15
    image: renjie.azurecr.io/deepfashion-gpu-image:latest
    command: ["sleep"]
    args: ["infinity"]
    stdin: true
    tty: true
    env:
    - name: GPU_CORE_UTILIZATION_POLICY
      value: "force"
    resources:
      limits:
        nvidia.com/gpu: 1
        nvidia.com/gpumem-percentage: 6
        nvidia.com/gpucores: 6
    volumeMounts:
    - name: shm
      mountPath: /dev/shm
  volumes:
  - name: shm
    emptyDir:
      medium: Memory
      sizeLimit: 32Gi
  restartPolicy: OnFailure

