# 8 GPU pods that can share the same GPU with 10% GPU memory and 10% GPU cores each
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod1
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:18.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          nvidia.com/gpu: 1
          nvidia.com/gpumem-percentage: 10
          nvidia.com/gpucores: 10
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod2
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:18.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          nvidia.com/gpu: 1
          nvidia.com/gpumem-percentage: 10
          nvidia.com/gpucores: 10
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod3
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:18.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          nvidia.com/gpu: 1
          nvidia.com/gpumem-percentage: 10
          nvidia.com/gpucores: 10
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod4
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:18.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          nvidia.com/gpu: 1
          nvidia.com/gpumem-percentage: 10
          nvidia.com/gpucores: 10
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod5
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:18.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          nvidia.com/gpu: 1
          nvidia.com/gpumem-percentage: 10
          nvidia.com/gpucores: 10
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod6
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:18.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          nvidia.com/gpu: 1
          nvidia.com/gpumem-percentage: 10
          nvidia.com/gpucores: 10
---
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod7
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu:18.04
      command: ["bash", "-c", "sleep 86400"]
      resources:
        limits:
          nvidia.com/gpu: 1
          nvidia.com/gpumem-percentage: 10
          nvidia.com/gpucores: 10