apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
  labels:
    app: gpu-pod
spec:
  containers:
  - name: gpu-container
    image: nvidia/cuda:11.6.2-base-ubuntu20.04
    command: ["sleep"]
    args: ["infinity"]
    resources:
      limits:
        nvidia.com/gpu: 2  # Reduced from 2 to 1 GPU
      requests:
        nvidia.com/gpu: 2  # Reduced from 2 to 1 GPU
    volumeMounts:
    - name: shm
      mountPath: /dev/shm
  volumes:
  - name: shm
    emptyDir:
      medium: Memory
      sizeLimit: 4Gi
  restartPolicy: OnFailure
  tolerations:
  - key: "nvidia.com/gpu"
    operator: "Exists"
    effect: "NoSchedule"
  # Removing the nodeSelector to allow scheduling on any node with GPUs
